const HCSDLdata = [
    { name: 'Nguyễn Văn G', score: 1.0 },
    { name: 'Nguyễn Văn H', score: 0.5 },
    { name: 'Nguyễn Văn I', score: 0.0 },
    { name: 'Nguyễn Văn F', score: 1.5 },
    { name: 'Nguyễn Văn G', score: 1.0 },
    { name: 'Nguyễn Văn H', score: 0.5 },
    { name: 'Nguyễn Văn B', score: 3.5 },
    { name: 'Nguyễn Văn C', score: 3.0 },
    { name: 'Nguyễn Văn D', score: 2.5 },
    { name: 'Nguyễn Văn E', score: 2.0 },
    { name: 'Nguyễn Văn F', score: 1.5 },
    { name: 'Nguyễn Văn G', score: 1.0 },
    { name: 'Nguyễn Văn H', score: 0.5 },
    { name: 'Nguyễn Văn F', score: 1.5 },
    { name: 'Nguyễn Văn G', score: 1.0 },
    { name: 'Nguyễn Văn H', score: 0.5 },
    { name: 'Nguyễn Văn I', score: 0.0 },
    { name: 'Nguyễn Văn F', score: 1.5 },
    { name: 'Nguyễn Văn G', score: 1.0 },
    { name: 'Nguyễn Văn H', score: 0.5 },
    { name: 'Nguyễn Văn I', score: 0.0 },
    { name: 'Nguyễn Văn I', score: 0.0 },
];

const CNPMdata = [
    { name: 'Nguyễn Văn G', score: 1.0 },
    { name: 'Nguyễn Văn H', score: 0.5 },
    { name: 'Nguyễn Văn I', score: 0.0 },
    { name: 'Nguyễn Văn F', score: 1.5 },
    { name: 'Nguyễn Văn G', score: 1.0 },
    { name: 'Nguyễn Văn H', score: 0.5 },
    { name: 'Nguyễn Văn G', score: 1.0 },
    { name: 'Nguyễn Văn H', score: 0.5 },
    { name: 'Nguyễn Văn I', score: 0.0 },
    { name: 'Nguyễn Văn F', score: 1.5 },
    { name: 'Nguyễn Văn G', score: 1.0 },
    { name: 'Nguyễn Văn H', score: 0.5 },
    { name: 'Nguyễn Văn Z', score: 4.0 },
    { name: 'Nguyễn Văn Y', score: 3.5 },
    { name: 'Nguyễn Văn X', score: 3.0 },
    { name: 'Nguyễn Văn V', score: 2.5 },
    { name: 'Nguyễn Văn N', score: 2.0 },
    { name: 'Nguyễn Văn G', score: 1.0 },
    { name: 'Nguyễn Văn H', score: 0.5 },
    { name: 'Nguyễn Văn I', score: 0.0 },
    { name: 'Nguyễn Văn F', score: 1.5 },
    { name: 'Nguyễn Văn G', score: 1.0 },
    { name: 'Nguyễn Văn H', score: 0.5 },
    { name: 'Nguyễn Văn F', score: 1.5 },
    { name: 'Nguyễn Văn G', score: 1.0 },
    { name: 'Nguyễn Văn H', score: 0.5 },
];

module.exports = { HCSDLdata, CNPMdata };
